curr_id = 0
let topics = {
  people: "Who the Alexander Technique helps",
  causes: "The root cause",
  skills: "What is learned",
  methods: "How it is taught",
  mechanisms: "Why it works",
}
let explanations={people:[
  {id: curr_id++,
   title: "artists", 
   description: "<p>Artists such as dancers, singers, musicians and actors often experience difficulties during performance related to <ul><li>stage fright</li><li>staleness of well rehearsed pieces</li><li>being in a self-critical mindset</li></ul><p>Because the Alexander Technique helps us gain agency over the quality of our presence and the focus of our attention, this can help with many of the qualities that can not be improved through technical practice alone.<p>Additionally, when seeking precise technical control of their craft, artists sometimes find themselves in a micro-managing mindset with a lot of excess mental and physical tension. The Alexander Technique helps with exploring what is helpful/necessary and what is not."},
  {id: curr_id++,
  title: "athletes", description: "<p>For athletes, it is important to not waste effort and energy where it is not needed. The Alexander Technique helps ask the question of whether any movement can be made more easy, freeing up energy that can be directed towards speed, endurance, faster recovery times and less risk of injury from strainful repetition."},
  {id: curr_id++,
  title: "people in pain", description: "<p>Pain is strange. Sometimes it appears to be attributable to a direct physical cause. In other cases, scans and other medical diagnoses can struggle to identify the underlying issue. In all cases, pain appear to be a top-down perceptive construct created in the brain. The Alexander Technique can help by finding greater ease in movement, often reducing the excessive strain placed on an area where pain is experienced. <p>More than that, as it explores the question of where we have a sense of safety and agency in our mind-body experiences, the Alexander Technique can also bring about changes in how and when the brain constructs experiences of pain."},     
  {id: curr_id++,
  title: "neurodivergent people", description:"<p>People with neurodivergence who habitually mask can find it difficult to know which parts of their behaviour are them and which parts are the mask (or the trauma of having to mask/interact with a world that is not designed for their needs). Autism and ADHD seem to affect how attention is regulated, in ways that can be experienced positively (the ability to hyperfocus) or negatively (the experience of distress from needing to rapidly shift attention). Last, current discourse around neurodivergence often suggests an essentialist “you have X, so you are unable to do Y”, which is unhelpful unless it is always true for a particular person. The Alexander Technique can help with all these aspects as it works with our sense of self, our regulation of our attention, awareness and perception, and the question of what is actually within our agency at any given moment."},
  {id: curr_id++,
  title: "philosophers of the human experience", description:"Many branches of philosophy, particular phenomenology are concerned with the subjective human experience: what is it “like” to have free will, agency, perception, an embodied mind, etc.? As the Alexander Technique can be described as the study of thinking in relation to movement, many of these questions can be asked through the Alexander Technique, particularly in terms of having counterfactual new experiences that contradict what is assumed to be true."},
  {id: curr_id++,
  title: "people with gender disphoria", description:"As gender dysphoria is a sensation that is unpleasant and hard to address (even through surgery, clothing choices, etc.) it is often pushed away. The Alexander Technique’s approaches of self-compassion, allowing the “true self” to emerge, and bringing mind and body into alignment and freedom can help, as experienced <a href=” https://jonathonheather.co.uk/category/non-binary/“>for example by Jonathon Heather</a>."},
  {id: curr_id++,
  title: "learners of a skill", description:""},
  {id: curr_id++,
  title: "people with chronic conditions", description:`<p>Chronic or long-term conditions tend to be multi-factor and to have a "limit" where the medical profession says "there's not really much more we can do". The Alexander Technique does not propose to cure or treat the conditions themselves (whether they be Parkinsons, chemotherapy, or hypermobility). However, it can help with managing the experience of living <em>with</em> the condition and finding the adaptability and resources necessary to renew the discovery of "what it's like today" so that it is no worse that it needs to be.<p>Sometimes, the Alexander Technique helps more than expected with some factor (for example finding a stronger sense of connection through the joints for people with hypermobility) and the impact of that factor can be reduced, resulting in an easier experience of daily life, even the though the underlying condition is still fully present.`},
  {id: curr_id++,
  title: "people seeking change", description:""},
  {id: curr_id++,
  title: "people in helping roles", description:"When working with people who need (and are maybe paying for) our help, it’s easy to be overinvested. Therapists, body- workers, coaches and teachers are familiar with this problem. The self-care skills needed can be framed as having “healthy boundaries”, but how that is carried out in mind and body can be overlooked. Boundaries that are too visible or come into place with sudden force can be detrimental to the helping relationship. <p>The Alexander Technique teacher’s skillset includes being able to keep our own wellbeing as a priority, even as we enter into a helping relationship with another person. As the means whereby this is accomplished is applying the Alexander Technique, it is also a skill that can be taught as part of Alexander Technique lessons."},
],
causes: [
  {id: curr_id++,
   title: "mind-body fragmentation", 
   description: "<p>The separation of mind and body as distinct dimensions of human experiences is strongly built in to much of our current culture, particularly in the Western world. Because of this, our body experiences are often described and felt as 'other', and it is considered relatively normal to have a limited relationship with our body and our senses, provided the 'mind' is able to use the body in a satisfactory manner for its own goals (work, play, relationships and so on). Even in modern somatic/embodiment methods, the body is often considered as a separate intelligence to be tapped into by the mind. People's experiences of the Alexander Technique (and of other approaches that clearly accomplish a similar objective) suggest that there is a complex relationship between thought, perception and movement that can be explored through a form of wholeness where mind and body are not distinct, but integrated into a single experience."},
  {id: curr_id++,
  title: "habitual bracing", description: "<p>As we experience events throughout our lives, starting in early childhood, we develop habitual strategies, particularly for dealing with difficulty and uncertainty. Some of these involve forms of physical bracing, such as holding our shoulders or hips tight. Others invovle mental bracing, such as holding on tightly to our beliefs and identity. Although these bracings can be an effective strategy, providing us with a sense of safety and agency, they typically trade off a degree of movability and adaptability and often outlast their usefulness in the short or long term. <p>Maybe the way we made ourselves small to be unnoticed by school bullies no longer serves us in adulthood. Or maybe the degree to which we cut ourselves off from the overwhelm of a busy street in a big city carries over unhelpfully when we are home with our family. <p>The Alexander Technique allows us to question our habits of bracing and construct new habits where safety comes from being very quick to adapt to new circumstances, rather than being braced against them."},
  {id: curr_id++,
  title: "end gaining", description:"<p>One of the human tendencies addressed by the Alexander Technique is “end gaining”, which can be described as allowing the desire for an outcome (“what”) to take precedence over the means whereby it is achieved (“how”). This is a bit like caring more for reaching a destination than how expensive the trip was, whether the route taken was optimal, whether the journey was stressful and whether any traffic accidents were caused along the way. <p>The Alexander Technique helps us explore how the end gaining tendency affects us in our daily activities and notice (and intercept) those times where we are so focused on the outcome that we use ourselves poorly, with unnecessary strain or without finding enjoyment in the process."},
  {id: curr_id++,
  title: "faulty sensory appreciation", description:""},
  {id: curr_id++,
  title: "limited movement in our daily lives", description:""},
  {id: curr_id++,
  title: "modern capitalist society", description:""},
  {id: curr_id++,
  title: "the human condition", description:""},
  {id: curr_id++,
  title: "human neurology", description:"<p>Our brain can be thought of as a constant prediction machine that models the world and chooses appropriate actions based on what it has done previously in similar circumstances. As the outcome of such a choice is almost always some kind of physical movement (even the tiny movements our eyes and forehead make while we are thinking!), any regularly made choices will show up as patterns of movement, which in turn will feed back into the brain's model of the world. To make the process more efficient, some of these choices get bundled together in sequence, creating the basis for habits.<p>Because this is a predictive process, the brain is often planning actions in anticipation of what is happening, particularly where such anticipations have been effective in the past. So when we go to pick up a kettle, rather than wait to find out how heavy it is, the brain is already expecting it to be a certain weight (or more) and prepares accordingly. By time the weight has been perceived any excess tension is already there. Worse, while carrying out habits, new sensory information is perceived less. This makes sense. But it also creates an environment where the brain (and its control over our thinking and movement) is often not adapting fluidly to what is actually happening, so long as our intention is carried out: we picked up the kettle successfully, albeit inefficiently.<p>In addition, we have the kind of brain that is regulated by a pre-frontal cortex. It intervenes to keep our behaviour in line with our longer term goals, social niceties and so on. Part of this regulation appears to use some level of motor control, literally inhibiting or slowing down certain reactions by adding tension in the body to prevent it and other parts of our brain from running off and do their own thing.<p>The Alexander Technique works on applying inhibition without bracing. It gives the experience of having 'space' between stimulus and response, as if the predictive brain is be simultaneously more responsive to new sensory information, but less likely to jump ahead when it doesn't need to"},
],
skills: [
  {id: curr_id++,
  title: "inhibition and direction", description:"<p>The Alexander Technique can be described as mainly teaching two core “thinking skills”. The ability to inhibit and the ability to direct.<p>Inhibition is the ability to not respond in a habitual way to a given stimulus. This can happen in a general sense (we have come to a state of “quiet” where we do not respond habitually to any stimulus unless we choose to), or a more specific sense where we are able to withhold consent to responding in a certain way to a specific stimulus. Inhibition allows a new response to emerge, using our mind-body’s intelligence to find a way of responding that is not the habitual one, without having to know or micro-manage what the new response should be. For example, when my boss asks me why I have not yet finished the task I started last week, my habitual response might be to become defensive and over-explain the complexity of the task. By inhibiting that response I can hopefully find myself with the resources to understand an explain with clarity what the underlying issue is: the task is partially done, I have competing obligations, I don’t have sufficient knowledge, etc.<p><small>Note that although the “stimulus” and ”response” are used here, I am not making the strong claim that this is an accurate description of how we relate to the world.</small><p>Direction is the ability to organise our mind-body through thought that is typically directed at our physical organisation. FM Alexander described this as giving “guiding orders”. He distinguished primary directions from secondary directions.<p>Primary directions contribute to the inhibition of certain typical human responses that disorganise the body and allow a natural organisation to emerge (typically thought of as an expansive organisation of the head, neck, back, legs and arms where the head goes forward and up of the neck and back, the back lengthens and widens, the legs go forward and away from the back and the arms and shoulders widen). These thoughts can be carried through into movement, so that whatever movement happens, it does not disrupt the organisation.<p>Secondary directions are specific to a person or activity and involve the thoughts that deepen the whole pattern of organisation, or allow the inhibition of certain specific responses.<p>As the experience of successful direction is that it furthers inhibition, and the experience of successful inhibition is that it furthers direction, they can be thought of as being two sides to the same coin or of being in a mutually beneficial relationship. Although direction and its result may be described in purely physiological terms of how the mio-fascio-(neuro)-skeletal system is organised, it is often experienced as something deeper so that our engagement with the world integrates mind, body and spirit."},
  {id: curr_id++,
  title: "improved sensory appreciation", description:""},
  {id: curr_id++,
  title: "reduced reactivity", description:""},
  {id: curr_id++,
  title: "engaging the primary control", description:""},
  {id: curr_id++,
  title: "coming into embodied presence", description:""},
  {id: curr_id++,
  title: "coming into relationship with the world", description:""},
  {id: curr_id++,
  title: "staying with the means whereby", description:"<p>One of the human tendencies addressed by the Alexander Technique is “end gaining”, which can be described as allowing the desire for an outcome (“what”) to take precedence over the means whereby it is achieved (“how”). This is a bit like caring more for reaching a destination than how expensive the trip was, whether the route taken was optimal, whether the journey was stressful and whether any traffic accidents were caused along the way. <p>The Alexander Technique helps us explore how the end gaining tendency affects us in our daily activities and notice (and intercept) those times where we are so focused on the outcome that we use ourselves poorly, with unnecessary strain or without finding enjoyment in the process."},
  {id: curr_id++,
  title: "self-compassion and self-regulation", description:""},
  {id: curr_id++,
  title: "finding safety in adaptability", description:""},
  {id: curr_id++,
  title: "constructive conscious control", description:"“Constructive conscious control” is the phrase that FM Alexander used to describe the aim of his technique. He contrasted it with “unconscious” control: when we seek to control our movements and thoughts to achieve a goal, unconscious habits take over. Alexander’s proposal involves constructing new, conscious habits with consideration for how we can best use ourselves in our totality, without micromanaging or applying unnecessary strain. <p>Although the phrasing does not have direct appeal in the 21st century, it’s worth considering that a lot of our unnecessary strain happens when we are experiencing a lack of agency, be it in a conversation or in trying to accomplish a physical task. It is then a frequent pattern that we brace and hold on tight, in an (often misguided) effort to gain more agency or certainty (i.e. control). Having conscious constructive control enables us to seek agency and certainty without losing adaptability and resilience in the process.<p>When used in the phrase “conscious guidance and control”, FM Alexander may also have meant that when seeking greater agency over our movement, the phases of guidance and control should be separate. Guidance refers to the thinking applied during the movement, whereas control refers to finding out after the fact whether the thinking achieved the desired movement goal. Jeando Masoero in particular claims that it is of particular importance to distinguish these phases and to have the control be observation in a mirror or a video, rather than the usual 'feeling whether it's right' that people tend to attempt to apply during the movement itself."},
  {id: curr_id++,
  title: "use of the self", description:"FM Alexander coined the term “use of the self” as a way of describing the quality of how we “use” ourselves, drawing the parallel with how we use tools. The outcome of learning the Alexander Technique is improved  “use”.<p>As he developed his understanding of use, he found that it has a general quality that affects all more specific functioning (such as how we breathe, how we move, or how we tell a joke). He also found that improved use goes hand in hand with an improved coordination or organisation of the relationship between the head, neck and torso.<p>In his book “The Use of the Self” he concluded that “use” and “manner of reaction” are the same thing: use is how we respond to and interact with the world. Someone with good use will tend to be perceived as poised, settled, unflappable and well-regulated. <p>Margaret Goldie used to describe this quality as “quiet throughout, yet more alert than ever before”."},
  {id: curr_id++,
  title: "exploring the agency available to us", description:""},
  {id: curr_id++,
  title: "thinking in activity", description:""},
  {id: curr_id++,
  title: "changing our habits", description:""},
],
methods: [
  {id: curr_id++,
  title: "using hands on to give an experience", description:"<p>The classical explanation for teaching the Alexander Technique is that the hands of the teacher are placed on the student in the form of gentle adjustment so that they may have an experience of what is desired as an outcome. This might be 'correct' organisation of the head, neck and back, a sense of newness, or a sense of lightness and greater ease. Having familiarity with this outcome, and some experience of how it has been achieved, the student is then more able to reproduce it for themselves."},
  {id: curr_id++,
  title: "using hands on to allow a unified self to emerge", description:"<p>The way the teacher puts hands on their student involves a high quality of 'staying back'. The teacher stays connected to themselves and does not allow their interest in the student to pull them out of that connection. Simultaneously, the teacher allows themself to enter into relationship with the student and have a sense of where the student is experiencing fragmentation and where a greater degree of wholeness of mind, body and spirit could emerge. <p>As a result students tend to experience the space to be themselves without feeling obliged to change. Simultaneously when their thoughts and movements take them into greater wholeness, the hands on provides support, reassurance and encouragement, so that this unfamiliar pattern has the chance to develop."},
  {id: curr_id++,
  title: "providing a sense of safety to our nervous system", description:""},
  {id: curr_id++,
  title: "providing stimuli that are within our ability to inhibit", description:""},
  {id: curr_id++,
  title: "using presence to share the teacher's skillset", description:"<p>In addition to teaching verbally with explanations or instructions, Alexander Technique teachers use the quality of their presence, particularly through their hands and their voice. As this quality is informed by their own ability to embody the Alexander Technique skills they are teaching, it serves as an example, a guide and form of co-regulation to help bring the student into a similar state of presence. This allows for a less cognitive form of learning where the resulting skill is then available to the student. This is also one of the ways the Alexander Technique can be taught online, using other forms of presence than hands."},
  {id: curr_id++,
  title: "entering into relationship and dialogue", description:""},
  {id: curr_id++,
  title: "direct instruction of the skills to be learned", description:""},
  {id: curr_id++,
  title: "cueing our psycho-physical organisation", description:""},
  {id: curr_id++,
  title: "providing compassion and unconditional positive regard", description:""},
],
mechanisms: [
  {id: curr_id++,
  title: "re-organising patterns of postural tone", description:"<p>This is the explanation for which there is most support in the scientific litterature around the Alexander Technique, not least because it is an operationalisable, measurable outcome that is cared about by researchers outside of the Alexander Technique community. Skilled Alexander Technique practitioners re-organise their postural tone better in adaptation to their surroundings. The Alexander Technique skills of inhibition, direction and sensory awareness are hypothesised as coming together to enhance the adaptivity of postural tone as an outcome."},
  {id: curr_id++,
  title: "activating the para-sympathetic nervous system", description:""},
  {id: curr_id++,
  title: "improving the body schema", description:""},
  {id: curr_id++,
  title: "increasing available sensory information", description:""},
  {id: curr_id++,
  title: "attunement to the pre-motor signals of habit", description:""},
  {id: curr_id++,
  title: "bringing our left and right brains into balance", description:""},
  {id: curr_id++,
  title: "interrupting the action sequences that underpin habits", description:"<p>In the brain, habits show up as “action sequences”. They are patterns of neural pathways firing one after the other, almost likely as once the “train track” of a given habit is engaged, it gets followed through to the end. These action sequences are resilient to new sensory information, sometimes even when it would render the action null and void. This is probably why you don’t notice when you forget to put a cup under your coffee machine in the morning. <p>An explanatory mechanism for the Alexander Technique could be that it disrupts the action sequence by bringing in greater sensory awareness, giving the action sequence a less “single track” quality, or not even engaging in the action sequence in the first place."},
  {id: curr_id++,
  title: "allowing our natural organisation to take over", description:""},
  {id: curr_id++,
  title: "our pre-frontal cortex having a less braced control", description:"<p>Aside from the meaning of 'inhibition' specific to the Alexander Technique (in which non-doing is a key component), 'inhibition' also describes part of the role of the pre-frontal cortex, whereby it intervenes to suppress and regulate behaviour that is being planned by other brain regions. Part of this control may involve muscular bracing, particularly around the neck and shoulders. Such bracing is often particularly visible in pre-teens who are just learning how to regulate their behaviour according to social norms.<p> This kind of braced control continues throught to adulthood, even as the pre-frontal cortex develops further and seems more capable to inhibit without muscular bracing. The Alexander Technique may work by helping relearn ways of exerting this kind of non-braced inhibition."},
  {id: curr_id++,
  title: "co-regulation", description:""},
],
}